// <auto-generated />
using System;
using DotNetEmpWebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetEmpWebAPI.Migrations
{
    [DbContext(typeof(EmpDbContext))]
    partial class EmpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetEmpWebAPI.Models.DeptTable", b =>
                {
                    b.Property<int>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("DeptID");

                    b.Property<string>("Dcity")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DCity");

                    b.Property<string>("Dname")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DName");

                    b.HasKey("DeptId")
                        .HasName("PK__DeptTabl__0148818E8095DD3F");

                    b.ToTable("DeptTable", (string)null);
                });

            modelBuilder.Entity("DotNetEmpWebAPI.Models.EmpTable", b =>
                {
                    b.Property<int>("Eid")
                        .HasColumnType("int");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("DeptID");

                    b.Property<DateOnly?>("Doj")
                        .HasColumnType("date")
                        .HasColumnName("DOJ");

                    b.Property<string>("Ename")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Eid")
                        .HasName("PK__EmpTable__C1971B53B8002F2F");

                    b.HasIndex("DeptId");

                    b.ToTable("EmpTable", (string)null);
                });

            modelBuilder.Entity("DotNetEmpWebAPI.Models.EmpTable", b =>
                {
                    b.HasOne("DotNetEmpWebAPI.Models.DeptTable", "Dept")
                        .WithMany("EmpTables")
                        .HasForeignKey("DeptId")
                        .HasConstraintName("FK__EmpTable__DeptID__5165187F");

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("DotNetEmpWebAPI.Models.DeptTable", b =>
                {
                    b.Navigation("EmpTables");
                });
#pragma warning restore 612, 618
        }
    }
}
